forge 'http://forge.puppetlabs.com'

mod 'puppetlabs/stdlib',    '5.1.0'
mod 'puppetlabs/mysql',     '7.0.0'
mod 'puppetlabs/translate', '1.2.0'
mod 'puppetlabs/apache',    '3.5.0'
mod 'puppetlabs/concat',    '5.2.0'
mod 'puppet/archive',       '3.2.1'
mod 'puppet/php',           '6.0.2'
mod 'puppet/zypprepo',      '2.2.2'
mod 'puppetlabs/apt',       '6.2.1'
mod 'puppetlabs/inifile',   '2.4.0'
